global:
  domain: argocd.kuxar.uk

server:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.kuxar.uk
    path: /
    pathType: Prefix
    annotations: {}
    tls: false

configs:
  params:
    server.insecure: "true"
