server:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations: {}
    hosts:
      - host: argocd.kuxar.uk
        paths:
          - /
    tls: []

configs:
  params:
    server.insecure: "true"